## Hoja de Trabajo 8

### Roberto Ríos, 20979
### Javier Valle, 20159

In [62]:
# Imports necesarios.
import pandas as pd
import numpy as np
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import learning_curve

### 1. Use los mismos conjuntos de entrenamiento y prueba que utilizó en las hojas anteriores.

In [ ]:

# Conjuntos de entrenamiento y prueba de la Hoja 5.

# Abriendo el archivo clasficado.
datos = pd.read_csv('archivo_clasificado.csv')

# Limpieza de datos.
datos = datos.replace(to_replace='',value=0)
datos = datos.fillna(0)
cat = datos.select_dtypes(include=['object']).columns.to_list()
num = datos.select_dtypes(include=['number']).columns.to_list()

# Pasando todo a un Dataframe.
x = pd.DataFrame()
x[num] = datos[num]
x[cat] = datos[cat].apply(lambda x: pd.factorize(x)[0])
res = 'Clasificacion'
X = x.drop(res, axis=1)
y = datos[res]

# Imprimiendo la clasificación.
print("Clasificación: ", y)

# Divide los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Crea un clasificador de árbol de decisión
clf = tree.DecisionTreeClassifier( max_depth=4 )

# Entrena el clasificador en el conjunto de entrenamiento
clf.fit(X_train, y_train)

# # Accurancy.
print("Precisión:", clf.score(X_test, y_test))

fig, ax = plt.subplots(figsize=(12, 8))
tree.plot_tree(clf, fontsize=4, feature_names=y, filled=True)

# Abriendo el archivo clasficado.
datos = pd.read_csv('archivo_clasificado.csv')

# Limpieza de datos.
datos = datos.replace(to_replace='',value=0)
datos = datos.fillna(0)
cat = datos.select_dtypes(include=['object']).columns.to_list()
num = datos.select_dtypes(include=['number']).columns.to_list()

# Pasando todo a un Dataframe.
x = pd.DataFrame()
x[num] = datos[num]
x[cat] = datos[cat].apply(lambda x: pd.factorize(x)[0])
res = 'OverallCond'
X = x.drop(res, axis=1)
y = datos[res]

# Imprimiendo la clasificación.
print("OverallCond: ", y)

# Divide los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Crea un clasificador de árbol de decisión
clf = tree.DecisionTreeClassifier( max_depth=4 )

# Entrena el clasificador en el conjunto de entrenamiento
clf.fit(X_train, y_train)


# Accurancy.
print("Precisión:", clf.score(X_test, y_test))

# Haciendo una predicción.
y_pred = clf.predict(X_test)

print("Predicción:", y_pred)

fig, ax = plt.subplots(figsize=(12, 8))
tree.plot_tree(clf, fontsize=4, feature_names=y, filled=True)

### 2. Seleccione como variable respuesta la que creó con las categorías del precio de la casa.

In [4]:
# Abriendo el archivo.
datos = pd.read_csv("archivo_clasificado.csv")

# Quitando los na del dataset.
datos = datos.replace(to_replace='',value=0)
datos = datos.fillna(0)

datos

# Usando como variable de respuesta la variable categórica que especifica si la casa es barata, media o cara.
res = "Clasificacion"

datos[res]

0       1
1       0
2       1
3       0
4       1
       ..
1455    0
1456    1
1457    1
1458    0
1459    0
Name: Clasificacion, Length: 1460, dtype: int64

### 3. Genere  dos modelos  de  redes  neuronales  que  sean  capaz  de  clasificar  usando  la variable respuesta que categoriza las casas en baratas, medias y caras. Estos modelos deben tener  diferentes topologías y funciones de activación.

In [34]:
# Abriendo el archivo clasficado.
df = pd.read_csv('archivo_clasificado.csv')

le = LabelEncoder()
df['Clasificacion'] = le.fit_transform(df['Clasificacion'])

X = df.drop('Clasificacion', axis=1)
y = df['Clasificacion']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convertir y_train a una variable categórica one-hot encoded
num_classes = len(np.unique(y_train))
y_train = to_categorical(y_train, num_classes=num_classes)

# Imputar valores nulos en X_train y X_test
X_train = X_train.fillna('missing')
X_test = X_test.fillna('missing')

# One-hot encoding de variables categóricas en X_train y X_test
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
X_train = pd.get_dummies(X_train, columns=cat_cols)
X_test = pd.get_dummies(X_test, columns=cat_cols)

# Modelo 1: red neuronal con una capa oculta de 8 neuronas y función de activación ReLU
model1 = Sequential()
model1.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model1.add(Dense(num_classes, activation='softmax'))

# Compilar modelo
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelo
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Modelo 2: red neuronal con dos capas ocultas de 16 y 8 neuronas y función de activación sigmoidal
model2 = Sequential()
model2.add(Dense(16, input_dim=X_train.shape[1], activation='sigmoid'))
model2.add(Dense(8, activation='sigmoid'))
model2.add(Dense(num_classes, activation='softmax'))

# Compilar modelos
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelos
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)
model2.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)


### 4. Use los modelos para predecir el valor de la variable respuesta 

In [43]:
# Abriendo el archivo clasficado.
df = pd.read_csv('archivo_clasificado.csv')

le = LabelEncoder()
df['Clasificacion'] = le.fit_transform(df['Clasificacion'])

X = df.drop('Clasificacion', axis=1)
y = df['Clasificacion']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convertir y_train a una variable categórica one-hot encoded
num_classes = len(np.unique(y_train))
y_train = to_categorical(y_train, num_classes=num_classes)

# Imputar valores nulos en X_train y X_test
X_train = X_train.fillna('missing')
X_test = X_test.fillna('missing')

# One-hot encoding de variables categóricas en X_train y X_test
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
X_train = pd.get_dummies(X_train, columns=cat_cols)
X_test = pd.get_dummies(X_test, columns=cat_cols)

# Modelo 1: red neuronal con una capa oculta de 8 neuronas y función de activación ReLU
model1 = Sequential()
model1.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model1.add(Dense(num_classes, activation='softmax'))

# Compilar modelo
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelo
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Modelo 2: red neuronal con dos capas ocultas de 16 y 8 neuronas y función de activación sigmoidal
model2 = Sequential()
model2.add(Dense(16, input_dim=X_train.shape[1], activation='sigmoid'))
model2.add(Dense(8, activation='sigmoid'))
model2.add(Dense(num_classes, activation='softmax'))

# Compilar modelos
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelos
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)
model2.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Hacer predicciones con el modelo 1
y_pred1 = model1.predict(X_train)

# Hacer predicciones con el modelo 2
y_pred2 = model2.predict(X_train)


print("Predicción 1: ", y_pred1)
print("Predicción 2: ", y_pred2)



37/37 [==============================] - 0s 1ms/step
Predicción 1:  [[1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 ...
 [1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [2.716525e-26 1.000000e+00 0.000000e+00 0.000000e+00]
 [1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]]
Predicción 2:  [[0.7064693  0.274833   0.01562306 0.00307464]
 [0.7064693  0.274833   0.01562306 0.00307464]
 [0.7064693  0.274833   0.01562306 0.00307464]
 ...
 [0.7064693  0.274833   0.01562306 0.00307464]
 [0.7064693  0.274833   0.01562306 0.00307464]
 [0.7064693  0.274833   0.01562306 0.00307464]]


### 5. Haga las matrices de confusión respectivas.

In [55]:
# Abriendo el archivo clasificado.
df = pd.read_csv('archivo_clasificado.csv')

le = LabelEncoder()
df['Clasificacion'] = le.fit_transform(df['Clasificacion'])

X = df.drop('Clasificacion', axis=1)
y = df['Clasificacion']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# One-hot encoding de variables categóricas en X_train y X_test
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
X_train = pd.get_dummies(X_train, columns=cat_cols)
X_test = pd.get_dummies(X_test, columns=cat_cols)

# Convertir y_train a una variable categórica one-hot encoded
num_classes = len(np.unique(y_train))
if num_classes > 2:
    y_train = to_categorical(y_train, num_classes=num_classes)

# Modelo 1: red neuronal con una capa oculta de 8 neuronas y función de activación ReLU
model1 = Sequential()
model1.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model1.add(Dense(num_classes, activation='softmax'))

# Compilar modelo
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelo
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Modelo 2: red neuronal con dos capas ocultas de 16 y 8 neuronas y función de activación sigmoidal
model2 = Sequential()
model2.add(Dense(16, input_dim=X_train.shape[1], activation='sigmoid'))
model2.add(Dense(8, activation='sigmoid'))
model2.add(Dense(num_classes, activation='softmax'))

# Compilar modelos
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Hacer predicciones con el modelo 1
y_pred1 = model1.predict(X_train)
y_pred1_classes = np.argmax(y_pred1, axis=1)

# Hacer predicciones con el modelo 2
y_pred2 = model2.predict(X_train)
y_pred2_classes = np.argmax(y_pred2, axis=1)

print("Predicción 1: ", y_pred1)
print("Predicción 2: ", y_pred2)

# Crear la matriz de confusión para cada modelo
if num_classes == 2:
    cm1 = confusion_matrix(y_train, y_pred1_classes)
    cm2 = confusion_matrix(y_train, y_pred2_classes)
else:
    cm1 = confusion_matrix(np.argmax(y_train, axis=1), y_pred1_classes)
    cm2 = confusion_matrix(np.argmax(y_train, axis=1), y_pred2_classes)

print("Matriz de confusión modelo 1:")
print(cm1)
print("Matriz de confusión modelo 2:")
print(cm2)

37/37 [==============================] - 0s 1ms/step
Predicción 1:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 ...
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
Predicción 2:  [[0.43294168 0.3317805  0.14183202 0.09344583]
 [0.43294168 0.3317805  0.14183202 0.09344583]
 [       nan        nan        nan        nan]
 ...
 [0.43294168 0.3317805  0.14183202 0.09344583]
 [0.43294168 0.3317805  0.14183202 0.09344583]
 [0.43294168 0.3317805  0.14183202 0.09344583]]
Matriz de confusión modelo 1:
[[823   0   0   0]
 [324   0   0   0]
 [ 19   0   0   0]
 [  2   0   0   0]]
Matriz de confusión modelo 2:
[[823   0   0   0]
 [324   0   0   0]
 [ 19   0   0   0]
 [  2   0   0   0]]


### 6. Compare los resultados obtenidos con los diferentes modelos de clasificación usando redes neuronales en cuanto a efectividad, tiempo de procesamiento y equivocaciones (donde el algoritmo  se  equivocó  más,  donde  se  equivocó  menos  y  la  importancia  que  tienen  los errores). 

In [61]:
# Abriendo el archivo clasificado.
df = pd.read_csv('archivo_clasificado.csv')

le = LabelEncoder()
df['Clasificacion'] = le.fit_transform(df['Clasificacion'])

X = df.drop('Clasificacion', axis=1)
y = df['Clasificacion']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# One-hot encoding de variables categóricas en X_train y X_test
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
X_train = pd.get_dummies(X_train, columns=cat_cols)
X_test = pd.get_dummies(X_test, columns=cat_cols)

# Convertir y_train a una variable categórica one-hot encoded
num_classes = len(np.unique(y_train))
if num_classes > 2:
    y_train = to_categorical(y_train, num_classes=num_classes)

# Modelo 1: red neuronal con una capa oculta de 8 neuronas y función de activación ReLU
model1 = Sequential()
model1.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model1.add(Dense(num_classes, activation='softmax'))

# Compilar modelo
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelo
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Modelo 2: red neuronal con dos capas ocultas de 16 y 8 neuronas y función de activación sigmoidal
model2 = Sequential()
model2.add(Dense(16, input_dim=X_train.shape[1], activation='sigmoid'))
model2.add(Dense(8, activation='sigmoid'))
model2.add(Dense(num_classes, activation='softmax'))

# Compilar modelos
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Hacer predicciones con el modelo 1
y_pred1 = model1.predict(X_train)
y_pred1_classes = np.argmax(y_pred1, axis=1)

# Hacer predicciones con el modelo 2
y_pred2 = model2.predict(X_train)
y_pred2_classes = np.argmax(y_pred2, axis=1)

print("Predicción 1: ", y_pred1)
print("Predicción 2: ", y_pred2)

# Crear la matriz de confusión para cada modelo
if num_classes == 2:
    cm1 = confusion_matrix(y_train, y_pred1_classes)
    cm2 = confusion_matrix(y_train, y_pred2_classes)
else:
    cm1 = confusion_matrix(np.argmax(y_train, axis=1), y_pred1_classes)
    cm2 = confusion_matrix(np.argmax(y_train, axis=1), y_pred2_classes)

print("Matriz de confusión modelo 1:")
print(cm1)
print("Matriz de confusión modelo 2:")
print(cm2)

if num_classes == 2:
    acc1 = accuracy_score(y_train, y_pred1_classes)
    acc2 = accuracy_score(y_train, y_pred2_classes)
else:
    acc1 = accuracy_score(np.argmax(y_train, axis=1), y_pred1_classes)
    acc2 = accuracy_score(np.argmax(y_train, axis=1), y_pred2_classes)

print("Accuracy modelo 1: ", acc1)
print("Accuracy modelo 2: ", acc2)

37/37 [==============================] - 0s 1ms/step
Predicción 1:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 ...
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
Predicción 2:  [[0.1363871  0.33541837 0.3926438  0.13555074]
 [0.1363871  0.33541837 0.3926438  0.13555074]
 [       nan        nan        nan        nan]
 ...
 [0.1411127  0.35438678 0.364741   0.13975957]
 [0.1363871  0.33541837 0.3926438  0.13555074]
 [0.1363871  0.33541837 0.3926438  0.13555074]]
Matriz de confusión modelo 1:
[[823   0   0   0]
 [324   0   0   0]
 [ 19   0   0   0]
 [  2   0   0   0]]
Matriz de confusión modelo 2:
[[213   0 610   0]
 [ 64   0 260   0]
 [  2   0  17   0]
 [  0   0   2   0]]
Accuracy modelo 1:  0.7046232876712328
Accuracy modelo 2:  0.1969178082191781


### 7. Analice si no hay sobreajuste en los modelos. Use para esto la curva de aprendizaje.

In [63]:
# Abriendo el archivo clasificado.
df = pd.read_csv('archivo_clasificado.csv')

le = LabelEncoder()
df['Clasificacion'] = le.fit_transform(df['Clasificacion'])

X = df.drop('Clasificacion', axis=1)
y = df['Clasificacion']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# One-hot encoding de variables categóricas en X_train y X_test
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns
X_train = pd.get_dummies(X_train, columns=cat_cols)
X_test = pd.get_dummies(X_test, columns=cat_cols)

# Convertir y_train a una variable categórica one-hot encoded
num_classes = len(np.unique(y_train))
if num_classes > 2:
    y_train = to_categorical(y_train, num_classes=num_classes)

# Modelo 1: red neuronal con una capa oculta de 8 neuronas y función de activación ReLU
model1 = Sequential()
model1.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model1.add(Dense(num_classes, activation='softmax'))

# Compilar modelo
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Ajustar modelo
model1.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Modelo 2: red neuronal con dos capas ocultas de 16 y 8 neuronas y función de activación sigmoidal
model2 = Sequential()
model2.add(Dense(16, input_dim=X_train.shape[1], activation='sigmoid'))
model2.add(Dense(8, activation='sigmoid'))
model2.add(Dense(num_classes, activation='softmax'))

# Compilar modelos
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Hacer predicciones con el modelo 1
y_pred1 = model1.predict(X_train)
y_pred1_classes = np.argmax(y_pred1, axis=1)

# Hacer predicciones con el modelo 2
y_pred2 = model2.predict(X_train)
y_pred2_classes = np.argmax(y_pred2, axis=1)

print("Predicción 1: ", y_pred1)
print("Predicción 2: ", y_pred2)

# # Crear la matriz de confusión para cada modelo
# if num_classes == 2:
#     cm1 = confusion_matrix(y_train, y_pred1_classes)
#     cm2 = confusion_matrix(y_train, y_pred2_classes)
# else:
#     cm1 = confusion_matrix(np.argmax(y_train, axis=1), y_pred1_classes)
#     cm2 = confusion_matrix(np.argmax(y_train, axis=1), y_pred2_classes)

# print("Matriz de confusión modelo 1:")
# print(cm1)
# print("Matriz de confusión modelo 2:")
# print(cm2)

# if num_classes == 2:
#     acc1 = accuracy_score(y_train, y_pred1_classes)
#     acc2 = accuracy_score(y_train, y_pred2_classes)
# else:
#     acc1 = accuracy_score(np.argmax(y_train, axis=1), y_pred1_classes)
#     acc2 = accuracy_score(np.argmax(y_train, axis=1), y_pred2_classes)

# print("Accuracy modelo 1: ", acc1)
# print("Accuracy modelo 2: ", acc2)

train_sizes, train_scores, test_scores = learning_curve(
    model1, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)

train_scores_mean = np.mean(train_scores, axis=1)
train_scores_std = np.std(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)
test_scores_std = np.std(test_scores, axis=1)

plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                 train_scores_mean + train_scores_std, alpha=0.1,
                 color="r")
plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                 test_scores_mean + test_scores_std, alpha=0.1, color="g")
plt.plot(train_sizes, train_scores_mean, 'o-', color="r",
         label="Entrenamiento")
plt.plot(train_sizes, test_scores_mean, 'o-', color="g",
         label="Validación cruzada")

plt.legend(loc="best")
plt.show()

37/37 [==============================] - 1s 4ms/step
Predicción 1:  [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 ...
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
Predicción 2:  [[0.22803628 0.5078855  0.19872458 0.06535369]
 [0.22803628 0.5078855  0.19872458 0.06535369]
 [       nan        nan        nan        nan]
 ...
 [0.2378279  0.5025964  0.19610815 0.06346759]
 [0.22803628 0.5078855  0.19872458 0.06535369]
 [0.22803628 0.5078855  0.19872458 0.06535369]]


TypeError: Cannot clone object '<keras.engine.sequential.Sequential object at 0x0000020045EE7A90>' (type <class 'keras.engine.sequential.Sequential'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.

### 9. Seleccione ahora el SalesPrice como variable respuesta. 

In [ ]:
# Abriendo el archivo.
datos = pd.read_csv("archivo_clasificado.csv")

# Quitando los na del dataset.
datos = datos.replace(to_replace='',value=0)
datos = datos.fillna(0)

datos

# Usando como variable de respuesta la variable categórica que especifica si la casa es barata, media o cara.
res = "SalePrice"

datos[res]